export const darkTheme = {
    mode: "dark",
    HEADER_BACKGROUND_COLOR: "#202020",
    STATUS_BAR_STYLE: "light-content",
    STATUS_BAR_BACKGROUND_COLOR: "#202020",
    ICON_HEADER_COLOR: "#FFFFFF",
    FEEDBACK_TOUCH_COLOR: "#FFFFFF",
    HEADER_TITLE_COLOR: "#FFFFFF",
    BACKGROUND_PAGES_COLOR: "#181818",
    TEXT_PAGES: "#FFFFFF",
    ACTIVE_BOTTOM_TAB_ICON: "#FFFFFF",
    BOTTOM_TAB_BACKGROUND_COLOR: "#202020",
    COLOR_LOADING_PAGES: "#FFFFFF",
    COLOR_POSTS_HOME: "#202020",
    COLOR_REFRESH_ARROW: "#FFFFFF",
    COLOR_REFRESH_BACKGROUND: "#202020"
}

export const lightTheme = {
    mode: "light",
    HEADER_BACKGROUND_COLOR: "#FFFFFF",
    STATUS_BAR_STYLE: "dark-content",
    STATUS_BAR_BACKGROUND_COLOR: "#FFFFFF",
    ICON_HEADER_COLOR: "#000000",
    FEEDBACK_TOUCH_COLOR: "#D3D3D3",
    HEADER_TITLE_COLOR: "#000000",
    BACKGROUND_PAGES_COLOR: "#FFFFFF",
    TEXT_PAGES: "#000000",
    ACTIVE_BOTTOM_TAB_ICON: "#000000",
    BOTTOM_TAB_BACKGROUND_COLOR: "#FFFFFF",
    COLOR_LOADING_PAGES: "#000000",
    COLOR_POSTS_HOME: "#FFFFFF",
    COLOR_REFRESH_ARROW: "#000000",
    COLOR_REFRESH_BACKGROUND: "#FFFFFF"
}