export const darkTheme = {
    mode: "dark",
    PRIMARY_BACKGROUND_COLOR: "#202020",
    STATUS_BAR_STYLE: "light-content",
    STATUS_BAR_BACKGROUND_COLOR: "#202020",
    ICON_HEADER_COLOR: "#FFFFFF",
    FEEDBACK_TOUCH_COLOR: "#FFFFFF",
    HEADER_TITLE_COLOR: "#FFFFFF",
    BACKGROUND_PAGES_COLOR: "#181818",
    TEXT_PAGES: "#FFFFFF",
}

export const lightTheme = {
    mode: "light",
    PRIMARY_BACKGROUND_COLOR: "#FFFFFF",
    STATUS_BAR_STYLE: "dark-content",
    STATUS_BAR_BACKGROUND_COLOR: "#FFFFFF",
    ICON_HEADER_COLOR: "#000000",
    FEEDBACK_TOUCH_COLOR: "#D3D3D3",
    HEADER_TITLE_COLOR: "#000000",
    BACKGROUND_PAGES_COLOR: "#FFFFFF",
    TEXT_PAGES: "#000000",
}